############################################
#### Server
server:
  port: 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 2800
    threads:
      max: 250
      min-spare: 250



############################################
#### Spring
spring:
  application:
    name: msa-boilerplate  # TODO : 수정 후, 이 주석은 삭제하세요!
    # TODO : 서비스 도메인 약어 수정 후, 이 라인과 다음 라인은 삭제하세요!
    # TODO : https://lgu-cto.atlassian.net/wiki/spaces/LGUPLUSMSA/pages/888045703/ -> 4-2) 도메인 약어 항목 참고
    name-abbr: MB  # 서비스명 약어
    name-env: ${spring.application.name}-${spring.profiles.active}  # 서비스명 + 실행환경
    name-abbr-env: ${spring.application.name-abbr}  # 서비스명 약어 + 실행환경(Local,DEV,TEST에만 적용)
  lifecycle:
    timeout-per-shutdown-phase: 1m
  profiles:
    active: local

  #### Auto Configuration
  autoconfigure:
    exclude:
      # Spring Cloud Stream 자동 구성 제외
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.function.FunctionConfiguration

  #### Message Source
  messages:
    basename: messages/response
    encoding: utf-8

  #### Spring Data
  data:
    redis:
      repositories:
        enabled: false

  #### Data Source
  datasource:
    writer:
      minimum-idle: 25
      maximum-pool-size: 25
    reader:
      minimum-idle: 25
      maximum-pool-size: 25
    hikari:
      connection-timeout: 2700
      validation-timeout: 2100
      leak-detection-threshold: 59000
      max-lifetime: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  #### JPA
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 100
        default_batch_fetch_size: 100

  #### Cache - Redis
  cache:
    type: redis
  redis:
    timeout: 500  # Redis read timeout
    connect-timeout: 100

  #### Spring Cloud Stream
  cloud:
    stream:
      bindings:
        ## Inbound 채널 (메시지 수신 설정)
        sample-in:
          # Consumer Group
          group: group.${spring.application.name-env}
          # Topic
          destination: inbound-topic-${spring.application.name-env} # TODO : 수정 후, 이 주석은 삭제하세요!
          content-type: application/json
          consumer:
            max-attempts: 3

        # DLQ Inbound 채널 설정
        dlq-sample-in:
          # Consumer Group
          group: dlq.group.${spring.application.name-env}
          # Topic
          destination: dlq.inbound-topic-${spring.application.name-env} # TODO : 수정 후, 이 주석은 삭제하세요!

        # Outbound 채널 (메시지 발송 설정)
        # (보통 내부 MSA 서비스와 통신할 Topic을 정의하기 때문에 송/수신용의 동일한 토픽을 사용할 일은 거의 없으나 테스트를 위해 발송 채널 정의)
        sample-out:
          destination: outbound-topic-${spring.application.name-env} # TODO : 수정 후, 이 주석은 삭제하세요!

      # Kafka 설정
      # (Kafka, RabbitMQ, AWS SNS/SQS 등의 설정, 메시지 큐 변경 시 아래 부분만 수정하면 연동 및 비즈니스 로직은 수정할 필요가 없음)
      kafka:
        binder:
          auto-create-topics: true
          #auto-add-partitions: true
        bindings:
          sample-in:
            # Dead Letter Processing
            consumer:
              enableDlq: true
              # DLQ Topic
              dlqName: dlq.outbound-topic-${spring.application.name-env}



############################################
#### Logging
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}][%X{saId:-}][%X{stbMac:-}]"



############################################
#### Other Domain Application Service
service:
  subscriber:
    url: http://subscriber:8080
  vodlookup:
    url: http://vodlookup:8080
  programming:
    url: http://programming:8080



############################################
#### FeignClient
feign:
  client:
    config:
      default: # @FeignClient의 value/name 속성 (default는 전체 적용)
        connectTimeout: 3000
        readTimeout: 3000
        #### Logging Level
        # NONE    : 미로깅 (Default)
        # BASIC   : Request Method, URL, Response 상태 코드, 실행 시간 로깅
        # HEADERS : Request, Response Header, 기본정보 로깅
        # FULL    : Request, Response Header, Response Body, 메타정보 로깅
        loggerLevel: NONE
  httpclient:
    enabled: true
    connection-timeout: 2700
    max-connections: 100



############################################
#### Actuator
management:
  endpoint:
    health:
      enabled: true
  health:
    db:
      enabled: false
    redis:
      enabled: false

############################################
#### SpringDoc
springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /api-docs
  swagger-ui:
    path: swagger-ui.html
    displayRequestDuration: true
    doc-expansion: none
    operations-sorter: method
    config-url: /api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
