############################################
#### Spring
spring:
  application:
    name-env: ${spring.application.name-abbr}-DEV

  #### Open Tracing
  zipkin:
    enabled: true
    baseUrl: http://a86263e3b2fd34e2f839a47ee774aef8-8d8459fc78776e1e.elb.ap-northeast-2.amazonaws.com:9411/

  #### Data Source
  datasource:
    writer:
      jdbc-url: jdbc:postgresql://<<postgres.msa-template.write.host>>:<<postgres.msa-template.write.port>>,<<postgres.msa-template.read.host>>:<<postgres.msa-template.read.port>>/<<postgres.msa-template.write.db.mylgdb>>?targetServerType=primary&ApplicationName=${spring.application.name}
      username: <<postgres.msa-template.write.username>>
      password: <<postgres.msa-template.write.password>>
    reader:
      jdbc-url: jdbc:postgresql://<<postgres.msa-template.write.host>>:<<postgres.msa-template.write.port>>,<<postgres.msa-template.read.host>>:<<postgres.msa-template.read.port>>/<<postgres.msa-template.write.db.mylgdb>>?targetServerType=preferSecondary&loadBalanceHosts=true&ApplicationName=${spring.application.name}
      username: <<postgres.msa-template.read.username>>
      password: <<postgres.msa-template.read.password>>

  ## Cache - Redis
  cache:
    type: redis
  redis:
    cluster:
      nodes: [<<redis.cluster.nodes>>]

  #### Spring Cloud Stream
  cloud:
    stream:
      kafka:
        binder:
          brokers: [<<kafka.msa.plaintext.bootstrapservers>>]



############################################
#### Logging
logging:
  level:
    com.lguplus.fleta: DEBUG
    org.hibernate:
      SQL: DEBUG



############################################
## FeignClient
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
