############################################
#### Server
server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 300
      min-spare: 150



############################################
####  Spring
spring:
  application:
    name: msa-boilerplate  # TODO : 이 부분 수정 후, 이 주석은 삭제하세요!
  lifecycle:
    timeout-per-shutdown-phase: 1m
  profiles:
    active: local

  #### Open Tracing
  #  zipkin:
  #    baseUrl: http://localhost:9411/

  #### Message Source
  messages:
    basename: messages/response
    encoding: utf-8

  #### Data Source
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 20000
      leak-detection-threshold: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  #### JPA
  jpa:
    open-in-view: false

  #### Redis
  redis:
    timeout: 500  # Redis read timeout
    connect-timeout: 50

  ## Message Stream - Kafka
  kafka:
    consumer:
      # ACK 자동 전송 여부 (true-자동, false-별도 코드 구성)
      enable-auto-commit: true
      # Consumer Offset이 없는 경우 처리 (latest-가장 마지막 offset부터, earliest-가장 처음 offset부터, none-에러 발생)
      auto-offset-reset: latest
      #max-poll-records: 1000



############################################
####  Logging
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}][%X{saId:-}][%X{stbMac:-}]"



############################################
## FeignClient
feign:
  client:
    config:
      default:  # @FeignClient의 value/name 속성 (default는 전체 적용)
        connectTimeout: 2000
        readTimeout: 2000
        #### Logging Level
        # NONE    : 미로깅 (Default)
        # BASIC   : Request Method, URL, Response 상태 코드, 실행 시간 로깅
        # HEADERS : Request, Response Header, 기본정보 로깅
        # FULL    : Request, Response Header, Response Body, 메타정보 로깅
        loggerLevel: NONE
