############################################
#### Server
server:
  port: 8080



############################################
####  Spring
spring:
  #### Open Tracing
  zipkin:
    baseUrl: http://localhost:9411/

  #### Data Source
  datasource:
    writer:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      minimum-idle: 5
      maximum-pool-size: 5
    reader:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      minimum-idle: 10
      maximum-pool-size: 10

  #### JPA
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop # FIXME : 반드시 제거
      use-new-id-generator-mappings: true # FIXME : false로 변경
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    #show-sql: true

  ## Cache - Redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 0

  ## Message Stream - Kafka
  kafka:
    bootstrap-servers: [ localhost:9092 ]



############################################
####  Logging
logging:
  level:
    com.lguplus.fleta: DEBUG
    org.hibernate:
      SQL: DEBUG
      #type: DEBUG
      #type.descriptor.sql: DEBUG
  pattern:
    level: "%5p [${spring.application.name}][%X{saId:-}][%X{stbMac:-}]"



############################################
#### Other Domain Application Service
service:
  msa-boilerplate:
    url: http://localhost:8080
  vodlookup:
    url: http://vodlookup.fleta.com
  programming:
    url: http://programming.fleta.com



############################################
## FeignClient
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
