############################################
#### Server
server:
  tomcat:
    threads:
      max: 300
      min-spare: 150



############################################
####  Spring
spring:
  profiles:
    active: local
    #  - local
#  main:
#    allow-bean-definition-overriding: false

  messages:
    basename: messages/response
    encoding: utf-8

  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 20000
      leak-detection-threshold: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    open-in-view: false

  #### Redis
  redis:
    # Redis read timeout
    timeout: 500
    connect-timeout: 50



############################################
####  Logging
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [%X{traceId}]"
